// src/firebase/config.ts

// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// Follow the instructions in the Firebase Console to set up your Firebase project.
// Navigate to Project Settings > General, and select the "Web" platform.
// From there, you can copy and paste the configuration object into the object below.
// For more information, see: https://firebase.google.com/docs/web/setup

export const firebaseConfig = {
  apiKey: "your-api-key",
  authDomain: "your-auth-domain",
  projectId: "your-project-id",
  storageBucket: "your-storage-bucket",
  messagingSenderId: "your-messaging-sender-id",
  appId: "your-app-id",
};
